---

- name: Configure KUBELET_EXTRA_ARGS.
  lineinfile:
    path: '/etc/systemd/system/kubelet.service.d/10-kubeadm.conf'
    line: "Environment=\"KUBELET_EXTRA_ARGS=--pod-manifest-path=/etc/kubernetes/manifests {{ kubernetes_kubelet_extra_args }} \""
    regexp: '^Environment=KUBELET_EXTRA_ARGS='
    state: present
  register: kubelet_config_file

- name: Reload systemd unit if args were changed.
  systemd:
    state: restarted
    daemon_reload: true
    name: kubelet
  when: kubelet_config_file is changed

- name: Ensure kubelet is started and enabled at boot.
  service:
    name: kubelet
    state: started
    enabled: true
