---

- name: Load a variable file based on the OS type, or a default if not found. Using free-form to specify the file.
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
    - default.yml

- name: include Ubuntu prepare tasks
  import_tasks: prepare-ubuntu.yml
  when: ansible_distribution == "Ubuntu"

- name: include CentOS prepare tasks
  import_tasks: prepare-centos.yml
  when: ansible_distribution == "CentOS"

- name: include install tasks
  import_tasks: install.yml

- name: '{{ kubernetes_kubeadm_config_file_path }}'
  file:
    state: directory
    path: '{{ kubernetes_kubeadm_config_file_path }}'

- name: '{{ kubernetes_kubeadm_config_file }}'
  template:
    src: clusterconfig.yaml.j2
    dest: '{{ kubernetes_kubeadm_config_file }}'

- name: ensure cloud provicer conf exists
  template:
    src: cloud.conf.j2
    dest: "{{ kubernetes_cloud_config_file }}"
  when: kubernetes_cloud_provider != ""

- name: ensure kubelet env KUBELET_EXTRA_ARGS is set
  lineinfile:
    path: '{{ kubernetes_kubelet_environment_file }}'
    regexp: '^KUBELET_EXTRA_ARGS.*'
    line: 'KUBELET_EXTRA_ARGS="--node-ip={{ ansible_host | default(ansible_default_ipv4.address) }}"'

- name: include etcd tasks
  include_tasks: etcd.yml
  when: inventory_hostname in groups.etcd

- name: include master with etcd prepare tasks
  include_tasks: prepare_master_with_etcd.yml
  when:
    - inventory_hostname in groups.k8s_masters
    - inventory_hostname in groups.etcd

- name: include master tasks
  include_tasks: master.yml
  when: inventory_hostname in groups.k8s_masters

- name: include network plugin tasks
  include_tasks: network_plugin.yml
  when: inventory_hostname == groups.k8s_masters[0]

- name: include cloud-provider tasks
  include_tasks: cloud_provider.yml
  when: inventory_hostname == groups.k8s_masters[0]

- name: include join worker tasks
  include_tasks: join.yml
  when: inventory_hostname not in groups.k8s_masters

#- name: include update master tasks
#  include_tasks: update_master.yml
#  when: inventory_hostname in groups.k8s_masters
#  tags: k8s_update
