---

- name: Load a variable file based on the OS type, or a default if not found. Using free-form to specify the file.
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
    - default.yml

- name: include Ubuntu prepare tasks
  import_tasks: prepare-ubuntu.yml
  when: ansible_distribution == "Ubuntu"

- name: incluse CentOS prepare tasks
  import_tasks: prepare-centos.yml
  when: ansible_distribution == "CentOS"

- name: include install tasks
  import_tasks: install.yml

- name: ensure folder kubeadm exists
  file:
    state: directory
    path: /etc/kubernetes/kubeadm

- name: ensure kubeadm config exists
  template:
    src: kubeadmconf.yaml.j2
    dest: /etc/kubernetes/kubeadm/kubeadmconf.yaml

- name: include etcd tasks
  include_tasks: etcd.yml
  when: inventory_hostname in groups.etcd

- name: include master tasks
  include_tasks: master.yml
  when: inventory_hostname in groups.k8s_masters

- name: include network plugin tasks
  include_tasks: network_plugin.yml

- name: include join tasks
  include_tasks: join.yml
  when: inventory_hostname == groups.k8s_masters[0]
