---

- name: ensure folder pki/etcd exists
  file:
    state: directory
    path: /etc/kubernetes/pki/etcd

- name: copy etcd cert files to master nodes
  copy:
    src: "/tmp/etcd{{ item }}"
    dest: "{{ item }}"
  with_items:
    - /etc/kubernetes/pki/etcd/ca.crt
    - /etc/kubernetes/pki/apiserver-etcd-client.crt
    - /etc/kubernetes/pki/apiserver-etcd-client.key

- name: initial at first master
  shell: "kubeadm init --config /etc/kubernetes/kubeadm/kubeadmconf.yaml"
  register: init_output
  when: inventory_hostname == groups.kube_masters[0]

- debug: var=init_output
  when: inventory_hostname == groups.kube_masters[0]

- name: incluse CentOS prepare tasks
  include: master-ha.yml
  when: ( groups.kube_master | length > 1 ) and inventory_hostname != groups.kube_masters[0]
