---

- name: get config files from primary master
  delegate_to: "{{ groups.k8s_masters[0] }}"
  slurp:
    src: "{{ item }}"
  with_items:
    - /etc/kubernetes/pki/ca.crt
    - /etc/kubernetes/pki/ca.key
    - /etc/kubernetes/pki/sa.key
    - /etc/kubernetes/pki/sa.pub
    - /etc/kubernetes/pki/front-proxy-ca.crt
    - /etc/kubernetes/pki/front-proxy-ca.key
    - /etc/kubernetes/admin.conf
  register: master_certs_configs_register

- name: copy config files to all masters
  copy:
    content: '{{ item.content | b64decode }}'
    dest: "{{ item.source }}"
  with_items: "{{ master_certs_configs_register.results }}"

- name: check master certs exists
  stat:
    path: "{{ item }}"
  register: master_certs_result
  with_items:
    - /etc/kubernetes/pki/apiserver-kubelet-client.crt
    - /etc/kubernetes/pki/apiserver-kubelet-client.key
    - /etc/kubernetes/pki/apiserver.crt
    - /etc/kubernetes/pki/apiserver.key
    - /etc/kubernetes/pki/front-proxy-client.crt
    - /etc/kubernetes/pki/front-proxy-client.key

- name: gen certs on master ha nodes
  command: kubeadm alpha phase certs all --config /etc/kubernetes/kubeadm/kubeadmconf.yaml
  when: (
    master_certs_result.results[0].stat.exists == False or
    master_certs_result.results[1].stat.exists == False or
    master_certs_result.results[2].stat.exists == False or
    master_certs_result.results[3].stat.exists == False or
    master_certs_result.results[4].stat.exists == False or
    master_certs_result.results[5].stat.exists == False )

- name: write kubelet config on master ha nodes
  command: kubeadm alpha phase kubelet config write-to-disk --config /etc/kubernetes/kubeadm/kubeadmconf.yaml
  changed_when: false

#- name: write kubelet env on master ha nodes
#  command: kubeadm alpha phase kubelet write-env-file --config /etc/kubernetes/kubeadm/kubeadmconf.yaml
#  changed_when: false
- name: incluse bug work around
  include: master-ha-bug-workaround.yml

- name: write kubelet systemd file on master ha nodes
  command: kubeadm alpha phase kubeconfig kubelet --config /etc/kubernetes/kubeadm/kubeadmconf.yaml
  changed_when: false

- name: Ensure kubelet is started and enabled at boot.
  service:
    name: kubelet
    state: started
    enabled: true

- name: check master admin conf exists
  stat:
    path: "{{ item }}"
  register: master_conf_result
  with_items:
    - /etc/kubernetes/admin.conf
    - /etc/kubernetes/controller-manager.conf
    - /etc/kubernetes/kubelet.conf
    - /etc/kubernetes/scheduler.conf

- name: write kubeconfig files for control-plane on master ha nodes
  command: kubeadm alpha phase kubeconfig all --config /etc/kubernetes/kubeadm/kubeadmconf.yaml
  when: (
    master_conf_result.results[0].stat.exists == False or
    master_conf_result.results[1].stat.exists == False or
    master_conf_result.results[2].stat.exists == False or
    master_conf_result.results[3].stat.exists == False )

- name: check master manifests exists
  stat:
    path: "{{ item }}"
  register: master_manifest_result
  with_items:
    - /etc/kubernetes/manifests/kube-apiserver.yaml
    - /etc/kubernetes/manifests/kube-controller-manager.yaml
    - /etc/kubernetes/manifests/kube-scheduler.yaml

- name: write controle-plane manifests on master ha nodes
  command: kubeadm alpha phase controlplane all --config /etc/kubernetes/kubeadm/kubeadmconf.yaml
  when: (
    master_manifest_result.results[0].stat.exists == False or
    master_manifest_result.results[1].stat.exists == False or
    master_manifest_result.results[2].stat.exists == False )

- name: annotate cri on master ha nodes
  command: kubeadm alpha phase kubelet config annotate-cri --config /etc/kubernetes/kubeadm/kubeadmconf.yaml
  changed_when: false

- name: mark as master on master ha nodes
  command: kubeadm alpha phase mark-master --config /etc/kubernetes/kubeadm/kubeadmconf.yaml
  changed_when: false
