---

- name: copy kubeadmconf
  copy:
    src: '{{ kubernetes_kubeadm_config_file }}'
    dest: '{{ kubernetes_kubeadm_config_file_path }}/kubeadmenvconf.yaml'
    remote_src: yes
  changed_when: false

- name: replace cluster-config with initial config
  lineinfile:
    path: '{{ kubernetes_kubeadm_config_file_path }}/kubeadmenvconf.yaml'
    regexp: '^kind: '
    line: 'kind: InitConfiguration'
  changed_when: false

- name: write kubelet env on master ha nodes
  command: kubeadm alpha phase kubelet write-env-file --config {{ kubernetes_kubeadm_config_file_path }}/kubeadmenvconf.yaml
  changed_when: false
