---

- name: "deploy canal network plugin #1"
  shell: "kubectl apply -f https://docs.projectcalico.org/v3.3/getting-started/kubernetes/installation/hosted/canal/rbac.yaml"
  when: inventory_hostname == groups.k8s_masters[0]

- name: "deploy canal network plugin #2"
  shell: "kubectl apply -f https://docs.projectcalico.org/v3.3/getting-started/kubernetes/installation/hosted/canal/canal.yaml"
  when: inventory_hostname == groups.k8s_masters[0]
