name: Ansible Playbook tests
on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1
        with:
          path: anmoel.kubernetes
      - name: checkout docker role
        uses: actions/checkout@v1
        with:
          repository: /anmoel/ansible-role-docker
          ref: master
          path: docker
      - name: prepare
        run: |
          ansible --version
          printf '[defaults]\nroles_path=/home/runner/work/ansible-role-kubernetes\nremote_user=gitlab\nprivate_key_file=~/id_rsa\nhost_key_checking=false\n' > ${HOME}/ansible.cfg
          echo ${GITHUB_WORKSPACE}
          echo "$ENCODED_SA_JSON" | base64 -d > ${GITHUB_WORKSPACE}/tests/serviceaccount.json
          echo "$ENCODED_SSH_KEY" | base64 -d > ${HOME}/id_rsa
        env: # Or as an environment variable
          ENCODED_SA_JSON: ${{ secrets.ENCODED_SA_JSON }}
          ENCODED_SSH_KEY: ${{ secrets.ENCODED_SSH_KEY }}
       - name: ansible lint
        uses: ansible/ansible-lint-action@master
        with:
          targets: "tests/site.yml"
          args: ""
      - name: ansible syntax check
        run: |
          ansible-playbook ${GITHUB_WORKSPACE}/tests/site.yml -i ${GITHUB_WORKSPACE}/tests/single_master/inventory --syntax-check
