name: Ansible Playbook tests
on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1
        with:
          path: anmoel.kubernetes
      - name: checkout docker role
        uses: actions/checkout@v1
        with:
          repository: /anmoel/ansible-role-docker
          ref: master
          path: docker
      - name: prepare
        run: |
          printf '[defaults]\nroles_path=/home/runner/work/ansible-role-kubernetes\nremote_user=gitlab\nprivate_key_file=/etc/ansible/id_rsa\nhost_key_checking=false\n' > /etc/ansible/ansible.cfg
          echo "$ENCODED_SA_JSON" | base64 -d > /builds/anmoel/ansible-role-kubernetes/tests/serviceaccount.json
          echo "$ENCODED_SSH_KEY" | base64 -d > /etc/ansible/id_rsa
        env: # Or as an environment variable
          ENCODED_SA_JSON: ${{ secrets.ENCODED_SA_JSON }}
      - name: ansible lint
        uses: ansible/ansible-lint-action@master
        with:
          targets: "tests/site.yml"
          args: ""
      - name: ansible syntax check
        uses: ./.github/actions/ansible-playbook
        with:
          playbook: tests/site.yml
          inventory: tests/single_master/inventory
          options: --syntax-check
